# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import messenger_pb2 as messenger__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in messenger_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class MessengerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/Messenger/Connect',
                request_serializer=messenger__pb2.ClientInfo.SerializeToString,
                response_deserializer=messenger__pb2.ConnectionStatus.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/Messenger/SendMessage',
                request_serializer=messenger__pb2.Message.SerializeToString,
                response_deserializer=messenger__pb2.Empty.FromString,
                _registered_method=True)
        self.ReceiveMessages = channel.unary_stream(
                '/Messenger/ReceiveMessages',
                request_serializer=messenger__pb2.ClientInfo.SerializeToString,
                response_deserializer=messenger__pb2.Message.FromString,
                _registered_method=True)
        self.ShowMenu = channel.unary_unary(
                '/Messenger/ShowMenu',
                request_serializer=messenger__pb2.Empty.SerializeToString,
                response_deserializer=messenger__pb2.Menu.FromString,
                _registered_method=True)
        self.ChooseCategory = channel.unary_unary(
                '/Messenger/ChooseCategory',
                request_serializer=messenger__pb2.CategoryChoice.SerializeToString,
                response_deserializer=messenger__pb2.Empty.FromString,
                _registered_method=True)
        self.ChooseItem = channel.unary_unary(
                '/Messenger/ChooseItem',
                request_serializer=messenger__pb2.ItemChoice.SerializeToString,
                response_deserializer=messenger__pb2.Empty.FromString,
                _registered_method=True)


class MessengerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShowMenu(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChooseCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChooseItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessengerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=messenger__pb2.ClientInfo.FromString,
                    response_serializer=messenger__pb2.ConnectionStatus.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=messenger__pb2.Message.FromString,
                    response_serializer=messenger__pb2.Empty.SerializeToString,
            ),
            'ReceiveMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.ReceiveMessages,
                    request_deserializer=messenger__pb2.ClientInfo.FromString,
                    response_serializer=messenger__pb2.Message.SerializeToString,
            ),
            'ShowMenu': grpc.unary_unary_rpc_method_handler(
                    servicer.ShowMenu,
                    request_deserializer=messenger__pb2.Empty.FromString,
                    response_serializer=messenger__pb2.Menu.SerializeToString,
            ),
            'ChooseCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.ChooseCategory,
                    request_deserializer=messenger__pb2.CategoryChoice.FromString,
                    response_serializer=messenger__pb2.Empty.SerializeToString,
            ),
            'ChooseItem': grpc.unary_unary_rpc_method_handler(
                    servicer.ChooseItem,
                    request_deserializer=messenger__pb2.ItemChoice.FromString,
                    response_serializer=messenger__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Messenger', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Messenger', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Messenger(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Messenger/Connect',
            messenger__pb2.ClientInfo.SerializeToString,
            messenger__pb2.ConnectionStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Messenger/SendMessage',
            messenger__pb2.Message.SerializeToString,
            messenger__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Messenger/ReceiveMessages',
            messenger__pb2.ClientInfo.SerializeToString,
            messenger__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShowMenu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Messenger/ShowMenu',
            messenger__pb2.Empty.SerializeToString,
            messenger__pb2.Menu.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChooseCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Messenger/ChooseCategory',
            messenger__pb2.CategoryChoice.SerializeToString,
            messenger__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChooseItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Messenger/ChooseItem',
            messenger__pb2.ItemChoice.SerializeToString,
            messenger__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
